id: P4454C414
initial_creation_type: input
source_metadata:
  title: Amitābha and Sukhāvatī Series
  language: de
  description: 'Texts and practices related to Buddha Amitābha and his pure-land,
    the blissful western paradise of Sukhāvatī (bde ba can), including prayers of
    aspiration to be reborn in Sukhāvatī (bde smon):'
  volume:
    f94e0ae328c747ab8555f77286d1f1c5:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    6c12db70e7f941f7a0d326c9845e14f8:
      title: Prayer to Buddha Amitābha
      parent: Aspiration Prayers (bde smon)
    d7d332863aa446b2b0b93e3bc425d45d:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers (bde smon)
    25eff39f9ddf47e1badf20dc9b2bf0ca:
      title: Brief Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    f846140e1f7c44a9a89d79ee4b447a7a:
      title: Aspiration for the Land of Great Bliss
      parent: Aspiration Prayers (bde smon)
    922504bb1a2c4b6ead4fef8afd49f50b:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    eaaae140999143cba4c1ab5f7bd9bf12:
      title: Prayer of Aspiration Towards Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    e55b5c8ff20f40899792e2c8f2acaba4:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    03cda8740dae4240b09a1fde6cd7b0fa:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Aspiration Prayers (bde smon)
    eb576a4e0e3142c2811f0f0eb6a565b8:
      title: Prayer to Behold Amitābha in Dreams
      parent: Aspiration Prayers (bde smon)
    96273d1ef9fb47858612e82dedaffc6a:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Inscriptions
    606740079b2f4db8ace377ffd473094c:
      title: Brief Amitābha Sleeping Practice
      parent: Meditation
    14d3ab4e6c8b46fc9a5d741b48e8bf7c:
      title: Meditation on Amitābha
      parent: Meditation
    c5ad7f80a68e43679cdc343be0e4bc22:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
created_at: '2022-03-01T02:41:42.983958'
last_modified_at: '2022-03-01T02:41:42.983961'
